name: artic-ncov2019-illumina
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython=1.74
  - libxcb
  - matplotlib>=3.3.3
  - python>=3.7
  - bwa=0.7.17=pl5.22.0_2
  - samtools=1.10
  - bcftools=1.10
  - trim-galore=0.6.5
  - ivar=1.3
  - pysam=0.16.0.1
  - freebayes=1.3.5
  - bcftools=1.10
  - pyvcf=0.6.8
  - pyyaml=5.3.1
  - pip=19.3.1
  - gofasta
  - usher>=0.3.2
  - snakemake-minimal=6.4.1
  - minimap2=2.17
  - picard=2.25.2
  - fastqc=0.11.9
  - multiqc=1.11
  - nextclade_js=0.14.4
  - pip:
      - pandas >= 1.1
      - scikit-learn >= 0.23.1
      - git+https://github.com/cov-lineages/pangoLEARN.git
      - git+https://github.com/cov-lineages/pangolin.git
      - git+https://github.com/cov-lineages/constellations.git 
      - git+https://github.com/cov-lineages/scorpio.git
      - git+https://github.com/cov-lineages/pango-designation.git
