name: Update repo1

#on: push
on: 
 release:
  types:
    - created
    - published

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
       #with:
       #  token: ${{ secrets.REPO }}
     - name: Fetch release version for repo2
       shell: bash
       run: |
         echo Hello there! 
         curl -sL https://api.github.com/repos/sofstam/repo2/releases/latest | \
         jq -r ".tag_name" > versions/latest-version.txt
         echo "$(cat versions/latest-version.txt)"
     - name: Check for modified files
       id: git-check
       run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
     - name: Make new Dockerfile for latest release; commit
       if: steps.git-check.outputs.modified == 'true'
       run: |
         echo Hello!     
